version: "3.9"

services:

  # Redis = message queue
  redis:
    image: redis

  # PostgreSQL database
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes

    # Run init script automatically
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


  # Python vote frontend
  vote:
    build: ./vote
    ports:
      - "5000:80"
    depends_on:
      - redis


  # .NET worker
  worker:
    build: ./worker
    depends_on:
      - redis
      - db


  # Node results UI
  result:
    build: ./result
    ports:
      - "5001:80"
    depends_on:
      - db
